In [61]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import os


In [62]:
#importing the dataset
dataset = pd.read_csv('bank.csv')

In [63]:
X = dataset.iloc[:,3:13].values # Credit Score through Estimated Salary
y = dataset.iloc[:, 13].values # Exited

In [64]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [65]:
# Encoding categorical (string based) data. Country: there are 3 options: France, Spain and Germany
# This will convert those strings into scalar values for analysis
print(X[:8,1], '............as ')
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_X_country_encoder = LabelEncoder()
X[:,1] = label_X_country_encoder.fit_transform(X[:,1])
print(X[:8,1])

['France' 'Spain' 'France' 'France' 'Spain' 'Spain' 'France' 'Germany'] ............as 
[0 2 0 0 2 2 0 1]


In [66]:
# Geneder to binary encoding
print(X[:8,1], '............as ')
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_X_gender_encoder = LabelEncoder()
X[:,2] = label_X_gender_encoder.fit_transform(X[:,2])
print(X[:6,2])

[0 2 0 0 2 2 0 1] ............as 
[0 0 0 0 0 1]


In [67]:
countryhotencoder = OneHotEncoder(categorical_features = [1]) # 1 is the country column
X = countryhotencoder.fit_transform(X).toarray()

In [68]:
X = X[:,1:] 

In [69]:


# Splitting the dataset into the Training and Testing set.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)



In [70]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [71]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

In [72]:
# This adds the input layer (by specifying input dimension) AND the first hidden layer (units)
model.add(tf.keras.layers.Dense(activation = 'relu', input_dim = 11, units=6, kernel_initializer='uniform'))

In [73]:
# Adding the second hidden layer
# Notice that we do not need to specify input dim. 
model.add(tf.keras.layers.Dense(activation = 'relu', units=6, kernel_initializer='uniform')) 

In [74]:
# Adding the output layer
# Notice that we do not need to specify input dim. 
# we have an output of 1 node, which is the the desired dimensions of our output (stay with the bank or not)
# We use the sigmoid because we want probability outcomes
model.add(tf.keras.layers.Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform')) 


Compiling the Neural Network

In [75]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

Fitting the Neural Network

In [76]:
model.fit(X_train, y_train, batch_size=10, epochs=50)

Epoch 1/50
8000/8000 [==============================] - 1s 113us/step - loss: 1.2571 - acc: 0.6486
Epoch 2/50
8000/8000 [==============================] - 1s 67us/step - loss: 0.5118 - acc: 0.7964
Epoch 3/50
8000/8000 [==============================] - 1s 67us/step - loss: 0.4824 - acc: 0.7989
Epoch 4/50
8000/8000 [==============================] - 1s 67us/step - loss: 0.4632 - acc: 0.8011
Epoch 5/50
8000/8000 [==============================] - 1s 67us/step - loss: 0.4505 - acc: 0.8054
Epoch 6/50
8000/8000 [==============================] - 1s 69us/step - loss: 0.4386 - acc: 0.8120
Epoch 7/50
8000/8000 [==============================] - 1s 67us/step - loss: 0.4219 - acc: 0.8217
Epoch 8/50
8000/8000 [==============================] - 1s 69us/step - loss: 0.4022 - acc: 0.8336
Epoch 9/50
8000/8000 [==============================] - 1s 69us/step - loss: 0.3856 - acc: 0.8439
Epoch 10/50
8000/8000 [==============================] - 1s 67us/step - loss: 0.3745 - acc: 0.8482
Epoch 11/50
8000/8

Testing the ANN

In [77]:
y_pred = model.predict(X_test)
print(y_pred)

[[0.29103178]
 [0.33231422]
 [0.2262432 ]
 ...
 [0.19870453]
 [0.15371414]
 [0.14377767]]


Making the Confusion Matrix

In [78]:
y_pred = (y_pred > 0.5)
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [79]:
type(y_test)

numpy.ndarray

In [80]:
type(y_pred)

numpy.ndarray

In [81]:
from sklearn.metrics import confusion_matrix



In [82]:
cm = confusion_matrix(y_test, y_pred)

In [83]:


print (((cm[0][0]+cm[1][1])*100)/(cm[0][0]+cm[1][1]+cm[0][1]+cm[1][0]), '% of testing data was classified correctly')



85.35 % of testing data was classified correctly
